version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    command: npm run dev
    environment:
      - REDIS_URL=redis://default:secure_pass@redis:6379/0
      - ACCOUNTING_PROVIDER_URL=http://accounting-provider:4001/api
      - DECISION_ENGINE_URL=http://decision-engine:4002/api
    ports:
      - "4000:4000"
    volumes:
      - .:/backend/src
    depends_on:
      - redis
      - accounting-provider
      - decision-engine
    networks:
      - app-tier
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass secure_pass
    volumes:
      - cache:/data
    networks:
      - app-tier
  accounting-provider:
    build:
      context: ./accounting-provider
    command: npm run dev
    ports:
      - "4001:4001"
    volumes:
      - .:/accounting-provider/src
    networks:
      - app-tier
  decision-engine:
    build:
      context: ./decision-engine
    command: npm run dev
    ports:
      - "4002:4002"
    volumes:
      - .:/decision-engine/src
    networks:
      - app-tier
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-tier
    depends_on:
      - backend

volumes:
  cache:
    driver: local
