openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Demyst-Task accounting provider"
  description: accounting provider

paths:
  /balanceSheet:
    parameters:
      - name: businessName
        description: Name of the business
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/BusinessName"
      - name: yearEstablished
        description: Year the business was established in
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/YearEstablished"
    get:
      summary: get balance sheet
      responses:
        "200":
          description: Balance sheet of the business
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceSheet"
        404:
          description: Balance sheet not found for this business
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    BusinessName:
      description: Name of a unique business
      type: string
    YearEstablished:
      description: Year the business was established in
      type: string
    BalanceSheet:
      type: array
      items:
        type: object
        properties:
          year:
            type: integer
            minimum: 1500
            maximum: 3000
          month:
            type: integer
            minimum: 1
            maximum: 12
          profitOrLoss:
            type: integer
          assetsValue:
            type: integer
            minimum: 0
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
