openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Demyst-Task decision engine"
  description: decision engine

paths:
  /api/decide:
    parameters:
      - name: businessName
        description: Name of the business
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/BusinessName"
      - name: yearEstablished
        description: Year the business was established in
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/YearEstablished"
      - name: profitOrLossByYear
        description: Profit or loss by year
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/ProfitOrLossByYear"
      - name: preAssessment
        description: Pre-assessment of the business
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/PreAssessment"
    get:
      summary: get the final result
      responses:
        "200":
          description: Final result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        404:
          description: Balance sheet not found for this business
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    BusinessName:
      description: Name of a unique business
      type: string
    YearEstablished:
      description: Year the business was established in
      type: string
    ProfitOrLossByYear:
      description: Profit or loss by year
      type: integer
    PreAssessment:
      description: Pre-assessment of the business
      type: integer
      minimum: 20
      maximum: 100
      default: 20
    Result:
      description: final result
      type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
